import {Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Josefin = Josefin_Sans({
  
  subsets: ["latin"],
});

export const metadata = {
  title: "BoiGhor",
  description: "Generated by create BoiGhor",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${Josefin.className} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
       <div className="flex-1"> {children}</div>
       <Footer></Footer>

      </body>

    </html>
  );
}
